spring:
  redis:
    database: 0
    host: 10.0.40.235
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 5000

